name: "workflow tests"

on: push

jobs:
  github-variables-test:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: generate ssh key
        run: ssh-keygen -t rsa -N "" -f mykey

      - name: list key
        run: ls -lhra

      - name: cat key
        run: cat mykey.pub

      - name: set public key var
        id: vars
        run: echo ::set-output name=key_pub::$(cat mykey.pub)

      - name: echo key.pub as github var
        run: ${{ steps.vars.outputs.key_pub }}